### ISSUE TITLE
Calculate Genealogical Distance

### ISSUE THREAD

**Issue by samuelflock** [cs481-ekh/s24--1#10]
As a user, I want to be able to identify the genealogical distance between two entries in the dataset, because it’s required for my research.

## Definition of Done
- [ ] Performs recursive calculation using input file
- [ ] Provides correct calculation

## Tasks
- [ ] Create method to access input file and recursively calculate genealogical distance between individuals
